version: "3.2"
services:
    web:
        image: nginx
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            # restart_policy:
            #     condition: on_failure
        ports:
            - 8080:80
        # networks:
        #     - webserver
        # networks:
        #     webserver:
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8888:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role==manager]
        # networks:
        #     - webserver